### ISSUE TITLE
Hamling (Sweden)

### ISSUE THREAD

**Issue by cklugow** [cklugow/EBSI-VECTOR-Task-3.3#2]

**Comment by cklugow** [comment]
Enterprise wallet: igrant
Personal wallet: igrant

@fredrik: please confirm
1.     Onboarded to enterprise wallet - done
2.     onboarded to personal wallet - done
3.     ODI issued - done
4.     PoA issued - done

**Comment by fredrik** [comment]
Sorry, can't confirm.
