### ISSUE TITLE
Hashnet (Slovenia)

### ISSUE THREAD

**Issue by cklugow** [cklugow/EBSI-VECTOR-Task-3.3#3]

**Comment by cklugow** [comment]
enterprise wallet: Triveria
personal wallet: Triveria

@Tali: please confirm
1.     Onboarded to enterprise wallet - done
2.     onboarded to personal wallet - done
3.     ODI issued - done
4.     PoA issued - not done / is assistance needed?

CEO (Tadej) needs to issue PoA. 

Next step: Tali suggests a meeting with Tadej

**Comment by tali** [comment]
Sorry, but wrong tali.

**Comment by cklugow** [comment]
PoA issuance on 19/12/24

**Comment by cklugow** [comment]
PoA issued

**Comment by cklugow** [comment]
ODI needed to issued again (--> switch to v13) - Issuing failed --> Triveria will investigate

**Comment by cklugow** [comment]
DID: did:ebsi:z23HW8spffbiDUsACnxqB4qK

**Comment by cklugow** [comment]
Re-doing Hashnet Onboarding from scratch necessary (Thread from Martin/ Tali as of 21/12/24, 10:04) --> Issuance did not work because wallets were on different versions on EBSI

**Comment by cklugow** [comment]
challenge detected: DID-onboarding was not successul on pilot env (conformance works well) --> public keys not written correctly on EBSI (prob. due to change on the pilot environment)
Onboarding processes was repeated: error occured
The problem occurs for Triveria-Users - it is not clear whether other wallet providers are affected
EBSI-support has been contacted

**Comment by cklugow** [comment]
problem solved with EBSI support

Status Hashnet
- onboarded to enterprise wallet
- onboarded to personal wallet
- ODI issued
- PoA issued
